function mirr_print(parent)

% MIRR_PRIN  Prints MirrorFigure
%
%
% Erzeugt PrintControlWindow zum Vorgeben einer PRINT-Anweisung
%
% Entsprechend der Vorgaben (Device, Option, Printer- oder FileName)
%  wird nach betaetigen des PRINT-Buttons eine MatlabPrintAnweisung 
%  ausgefuehrt.
%
% Die Handles fuer die UiControlButtons stehen in der Globalen
%  Variablen Hpr0.
%
%  Mit GET und SET kann auf diese zugegriffen werden.
%
% Die Handles fuer den PRINT und BACK Button stehen in
%  der Globalen Variablen Hpr3
%


global MC  Hpr0 Hpr3


set(MC(6,4),'enable','off')  % PrintUIMenu


strings = ['Device Options                   ' ; ...
           'PrinterName                      ' ; ...
           'FileName                         ' ; ...
           '                                 ' ; ...
           '                                 ' ; ...
           'Additional Postscript Options    '   ]; 


%***************************************************
% CALLBACKS
%---------------------------------------------------
%
% function mirr_pncb




CC = computer;
Device = [];

if strcmp(lower(CC(1:2)),'pc')
  Device = [ Device;
'win       - Send figure to currently installed printer in monochrome   02';
'winc      - Send figure to currently installed printer in color        02';
'meta      - Send figure to clipboard in Metafile format                00';
'bitmap    - Send figure to clipboard in bitmap format                  00';
'cdj550    - HP Deskjet 550c                                            01';
'setup     - Bring up Print Setup messg box, but do not print          00' ];
end
 
  Device = [ Device;
'ps        - PostScript for black and white printers                    11';
'psc       - PostScript for color printers                              11';
'ps2       - Level 2 PostScript for black and white printers            11';
'psc2      - Level 2 PostScript for color printers                      11';
'eps       - Encapsulated PostScript (EPSF)                             11';
'epsc      - Encapsulated Color PostScript (EPSF)                       11';
'eps2      - Encapsulated Level 2 PostScript (EPSF)                     11';
'epsc2     - Encapsulated Level 2 Color PostScript (EPSF)               11';
'hpgl      - HPGL compatible with Hewlett-Packard 7475A plotter         01';
'ill       - Adobe Illustrator 88 compatible illustration file          03';
'mfile     - M-file that will mostly re-create Figure and its children  03' ];
 
 
if ~strcmp(lower(CC(1:2)),'ma')
  Device = [ Device;
'laserjet  - HP LaserJet                                                01';
'ljetplus  - HP LaserJet+                                               01';
'ljet2p    - HP LaserJet IIP                                            01';
'ljet3     - HP LaserJet III                                            01';
'cdeskjet  - HP DeskJet 500C with 1 bit/pixel color                     01';
'cdjcolor  - HP DeskJet 500C with 24 bit/pixel color HQ color           01';
'cdjmono   - HP DeskJet 500C printing black only                        01';
'deskjet   - HP DeskJet and DeskJet Plus                                01';                                
'paintjet  - HP PaintJet color printer                                  01';
'pjetxl    - HP PaintJet XL color printer                               01';
'bj10e     - Canon BubbleJet BJ10e                                      01';
'ln03      - DEC LN03 printer                                           01';
'epson     - Epson-compatible dot matrix printers (9- or 24-pin)        01';
'eps9high  - Epson-compatible 9-pin, interleaved lines (triple resol.)  01';
'gif8      - 8-bit color GIF file format                                01';
'pcx16     - Older color PCX file format (EGA/VGA, 16-color)            01';
'pcx256    - Newer color PCX file format (256-color)                    01' ]; 
end
 
PsOption = [ ...
'no options                                                      ';
'append    - Append, not overwrite, the graph to PostScript file ';
'epsi      - Add 1-bit deep bitmap preview (EPSI format)         ';
'ocmyk     - Use CMYK colors in PostScript instead of RGB        ';
'psdefcset - Use PostScript default character set encoding always' ];
 

scr_si = get(0,'screensize');


v = version;
if v(1) == '4'
property  = 'nextplot';
propvalue = 'add';
vs = 's';
else
property  = 'handlevisibility';
propvalue = 'callback';
vs = '';
end



fig=figure('position',[scr_si(3)-500  scr_si(4)-300  460 260], ...
            'color',[1 1 1], ...
            property,propvalue , ...
            'numbertitle','off', ...
            'menubar' , 'none' , ...
            'tag',get(parent,'tag'), ...
            'name', ['Print ' get(parent,'name')]);

set(fig,'userdata',[ parent ; fig ])

MC(6,3) = fig;



figpos = get(fig,'position');
             
axe = axes('position',[0 0 1 1], ...
     'visible','off'     , ...
     'xlim'   , [0 figpos(3)] , ...
     'ylim'   , [0 figpos(4)]        );




dist = 50;

Hpr0(parent,1) = uicontrol(   ...
  'parent',fig , ...
  'style' , 'popupmenu' , ...
  'string' , Device  , ...
  'value'  , 2 , ...
  'position' , [20 figpos(4)-dist-50 420  30 ] , ...
  'foregroundcolor' , [0 0 0] , ...
  'backgroundcolor' , [0.8 0.9 1] , ...
  'horizontalalignment' , 'left' , ...
   'callback'   , 'mirr_prcb(gcf,''device'')' );

% PrinterName
Hpr0(parent,2) = uicontrol(   ...
  'parent',fig , ...
  'style' , 'edit' , ...
  'max',2, ...
  'min',0, ...
  'position' , [20 figpos(4)-dist*3-50 120  30 ] , ...
  'foregroundcolor' , [0 0 0] , ...
  'backgroundcolor' , [0.8 0.9 1] , ...
  'horizontalalignment' , 'center' );

% FileName
Hpr0(parent,3) = uicontrol(   ...
  'parent',fig , ...
  'style' , 'edit' , ...
  'max',2, ...
  'min',0, ...
  'position' , [180 figpos(4)-dist*2-50 260  30 ] , ...
  'foregroundcolor' , [0 0 0] , ...
  'backgroundcolor' , [0.8 0.9 1] , ...
  'horizontalalignment' , 'center' );

Hpr0(parent,4) = uicontrol(   ...
  'parent',fig , ...
  'style' , 'checkbox' , ...
  'string' , 'Print only to File.'  , ...
  'value'  , 1 , ...
  'position' , [20 figpos(4)-dist*2-50 140  30 ] , ...
  'foregroundcolor' , [0 0 0] , ...
  'backgroundcolor' , [0.8 0.9 1] , ...
  'horizontalalignment' , 'left'  , ...
   'callback'   , 'mirr_prcb(gcf,''onlyf'')' ); 


Hpr0(parent,5) = uicontrol(   ...
  'parent',fig , ...
  'style' , 'pushbutton' , ...
  'string' , 'To Files ...'  , ...
  'position' , [340 figpos(4)-dist*3-50 100  30 ] , ...
  'foregroundcolor' , [0 0 0] , ...
  'backgroundcolor' , [0.8 0.9 1] , ...
  'horizontalalignment' , 'center' , ...
   'callback'   , 'mirr_prcb(gcf,''tofiles'')' ); 



  
Hpr0(parent,6) = uicontrol(   ...
  'parent',fig , ...
  'style' , 'popupmenu' , ...
  'string' , PsOption  , ...
  'value'  , 1 , ...
  'position' , [20 figpos(4)-dist*4-50 420  30 ] , ...
  'foregroundcolor' , [0 0 0] , ...
  'backgroundcolor' , [0.8 0.9 1] , ...
  'horizontalalignment' , 'left' );


eval(get(Hpr0(parent,1),'callback'))

 ww = [ 230 80 310 120 340 230 ];
jjj = [ 1 3 2 3 3 4 ];

for jj = [1 2 3  6]
   
  text( ww(jj) , figpos(4)-dist*jjj(jj)-40+20 , deblank(strings(jj,:)) , ...
                'parent',axe , ...
                'color'               , [0 0 0]  , ...
                'units'               , 'pixels' , ...
                'fontsize'            , 12       , ...
                'fontweight'          , 'bold'   , ...
                'horizontalalignment' , 'center' , ...
                'verticalalignment'   , 'bottom'         ) 
end


dist = 40;

Hpr3(parent,1) = uicontrol(   ...
  'parent',fig , ...
  'style' , 'pushbutton' , ...
  'string' , 'Print'  , ...
  'position' , [20 figpos(4)-dist*1 60  20 ] , ...
  'foregroundcolor' , [0 0 0] , ...
  'backgroundcolor' , [0.9 0.9 1] , ...
  'horizontalalignment' , 'center' , ...
   'callback'   , 'mirr_prcb(gcf,''print'')'  );

 Hpr3(parent,2) = uicontrol(   ...
  'parent',fig , ...
  'style' , 'pushbutton' , ...
  'string' , 'Back'  , ...
  'position' , [figpos(3)-80 figpos(4)-dist*1 60  20 ] , ...
  'foregroundcolor' , [0 0 0] , ...
  'backgroundcolor' , [0.8 0.8 1] , ...
  'horizontalalignment' , 'center' , ...
   'callback'   ,  'mirr_prcb(gcf,''back'')'  );

v = version;
if v(1) == '4'
 set(fig,'nextplot','replace')
end 


figure(fig)
